### ISSUE TITLE
Inverted values in characters array.

### ISSUE THREAD

**Issue by victle2003** [Tsukiapp/MAL-scrapper#1]
When fetching `"https://tsukiapi.herokuapp.com/anime/search?keyword={anime name}&type=anime"`, the returned information contains multiple object arrays. One of them is the `characters` array which returns 10 objects with the properties `name` and `img`.
The issue is that the values of said properties are inverted, having `name` the value of `img`, and `img` the value of `name`.
Here's an example: 

1. Let's fetch and log said url, specifying the array with the issue and one of its objects: 
```
function getAnimeInfo(animeName) {
    return new Promise((resolve, reject) => {
        resolve(fetch(`http://localhost:5000/anime/search?keyword=${animeName}&type=anime`, {mode: "no-cors"}))
        reject("ERROR")
    })
}

async function displayAnimeInfo(userInput) {
    try {
        const anime = await getAnimeInfo(userInput)
        const processedAnime = await anime.json()
        console.log(processedAnime.characters[0])
    } catch(error) {
        console.log(error)
    }
}

displayAnimeInfo("death note")
```

2. Let's check the logged object: `{name: "https://cdn.myanimelist.net/r/42x62/images/charact…/10/249647.jpg?s=95cecc21f3db10318c68a0863f0132c8", img: "Lawliet, L"}`

The value of `name` is a link of the character's image, and the value of `img` is a string with the name of the character.

**Comment by alejandro0619** [comment]
### ✅ Inverted values in character's array bug fixed.
The library has been updated to the version **[1.1.2.](https://www.npmjs.com/package/tsukiapp-mal-scrapper)**
⚠️ Make sure you have its latest version to prevent this unexpected behavior to happen.

**To update this library:**

1. Open your terminal.
2. Go to the root of your project:
`$ cd project-name `
3. Enter inside your terminal:
`$ npm update tsukiapp-mal-scrapper`
